# Generated by Django 5.2.7 on 2026-02-03 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_leader_user_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_settings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='update_time',
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='userreportsto',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can be a Staff Member.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepartmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.SmallIntegerField(db_default=1, default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_log', models.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserToDepartment',
        ),
    ]
