# Generated by Django 5.2.7 on 2026-02-28 00:43

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_editlog_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.DrmUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='departmenthead',
            old_name='user',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='editlog',
            old_name='user',
            new_name='log_user',
        ),
        migrations.RenameField(
            model_name='userreportsto',
            old_name='user',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='userreportsto',
            old_name='reports_to',
            new_name='reportsTo',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='department',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
