# Generated by Django 5.2.7 on 2025-11-23 09:56


"""
    Ignore this migration...
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options_user_is_staff'),
    ]

    operations = [
    ]
