# Generated by Django 5.2.7 on 2025-11-23 10:08

"""
    Ignore this migration...
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
    ]
