# Generated by Django 5.2.7 on 2026-02-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_workspace_workspacedepartment_workspacetasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacedepartment',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='workspacetasks',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
    ]
