# Generated by Django 5.2.7 on 2025-11-09 09:44

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_parent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='Task_id',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='Task_id',
        ),
        migrations.RemoveField(
            model_name='taskuserassignment',
            name='assignee_user_id',
        ),
        migrations.RemoveField(
            model_name='taskuserassignment',
            name='assignor_user_id',
        ),
        migrations.RemoveField(
            model_name='taskuserassignment',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='taskwatcher',
            name='Task_id',
        ),
        migrations.RemoveField(
            model_name='taskwatcher',
            name='watcher_user_id',
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creator_user_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='task',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asasignee_user', to=settings.AUTH_USER_MODEL)),
                ('assignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asasignor_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(max_length=20)),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('rawobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
        migrations.DeleteModel(
            name='TaskDetails',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='TaskUserAssignment',
        ),
        migrations.DeleteModel(
            name='TaskWatcher',
        ),
    ]
