# Generated by Django 5.2.7 on 2025-11-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_taskdetails_task_id_remove_taskstatus_task_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='deadline',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='details',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='visibility',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='watcher',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='details',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
    ]
